# Generated by Django 2.2.6 on 2019-11-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('done', models.BooleanField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
